package emirasepet;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

class VeritabaniYoneticisi {

    private static final String URL =
            "jdbc:h2:./data/emira_sepet_db;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE";

    static void baslat() {
        new File("data").mkdirs();
        try (Connection conn = baglantiAl(); Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS sepet ("
                    + "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "musteri_adi VARCHAR(100) NOT NULL, "
                    + "durum VARCHAR(50) DEFAULT 'aktif')");
            stmt.execute("CREATE TABLE IF NOT EXISTS sepet_urun ("
                    + "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "sepet_id INT NOT NULL, "
                    + "urun_adi VARCHAR(100) NOT NULL, "
                    + "adet INT DEFAULT 1, "
                    + "fiyat DECIMAL(18,2) NOT NULL, "
                    + "FOREIGN KEY (sepet_id) REFERENCES sepet(id) ON DELETE CASCADE)");
        } catch (SQLException e) {
            throw new RuntimeException("Veritabanı başlatılamadı: " + e.getMessage(), e);
        }
    }

    static Connection baglantiAl() throws SQLException {
        return DriverManager.getConnection(URL, "emira", "emira123");
    }
}
